// src/movies.ts
export const movies: string[] = [
  "Pirates of the Caribbean",
  "Sagan om ringen",
  "Jurassic Park",
  "Heat",
  "Hajen",
  "Band of Brothers",
  "Inception",
  "Nyckeln till frihet",
  "Se7en",
  "Gudfadern",
  "The Dark Knight",
  "Interstellar",
  "Pulp Fiction",
  "Fight Club",
  "Reservoir Dogs",
  "The Matrix",
  "John Wick",
  "Speed",
  "Juryn",
  "Da Vinci-koden",
  "Änglar och demoner",
  "Noll tolerans",
  "JFK",
  "Mission Impossible",
  "Hobbit",
  "Star Wars",
  "Bourne Identity",
  "Jagad",
  "Arn",
  "Robin Hood",
  "King Kong",
];